Repository streetcredlabs/categories, pull requests merged in 2019-06, with the labels that each got.

#27 add getCompleteness fn
  .gitignore
  .prettierrc
  dist/__test__/dump.test.d.ts
  dist/__test__/findById.test.d.ts
  dist/__test__/getCompleteness.test.d.ts
  dist/bundle.js
  dist/index.d.ts
  dist/utils/getCompleteness.d.ts
  dist/utils/transforms.d.ts
  package-lock.json
  package.json
  rollup.config.js
  src/__test__/dump.test.js
  src/__test__/dump.test.ts
  src/__test__/findById.test.js
  src/__test__/findById.test.ts
  src/__test__/getCompleteness.test.ts
  src/index.js
  src/index.ts
  src/utils/getCompleteness.ts
  src/utils/transforms.js
  src/utils/transforms.ts
  tsconfig.json
  tslint.json
  yarn.lock
Labels: in review, ready for review

#30 Add new categories to support SIC 8-digit import
  src/data/categories.json
Labels: in progress, ready for review

#39 Require phone for restaurants
  dist/bundle.js
  package.json
  src/data/categories.json
Labels: in-review
